apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: retail-app
type: Opaque
stringData:
  mysql-username: "dbadmin"
  mysql-password: "Bedrock2025!Secure"
  postgresql-username: "dbadmin"
  postgresql-password: "Bedrock2025!Secure"
